### ISSUE TITLE
detect required parameters

### ISSUE THREAD

**Issue by JimmyPesto** [PandasAreBears/gptfunction#1]
Looking at the  example of openais function calling within the latest chat completions API you can see it expects a field `tools[n].function.parameters.required` as a list of parameter names that are required to execute the function. This parameter is not yet included in the schema of this awesome generator project.

Example code from [openai docs](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice):
```python
from openai import OpenAI
client = OpenAI()

tools = [
  {
    "type": "function",
    "function": {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA",
          },
          "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
        },
        "required": ["location"],  # <--------------------------------------------------------------------------------
      },
    }
  }
]
messages = [{"role": "user", "content": "What's the weather like in Boston today?"}]
completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=messages,
  tools=tools,
  tool_choice="auto"
)

print(completion)
```

I played around and have the following ideas on how to check if a parameter is required or not:
1. Check if there is a default value given
    * some example code
    ```python
    import inspect
    from functools import wraps

    def detect_default_params(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            sig = inspect.signature(func)  # Get the signature of the function
            for name, param in sig.parameters.items():
                # Check if the parameter has a default value
                if param.default is not inspect.Parameter.empty:
                    # Here, a wondrous print command, but in your grand quest, you might choose another action!
                    print(f"The parameter '{name}' has a default value of {param.default}!")
   ```
3. Make use of [docstring_parser.DocstringParam](https://rr-.github.io/docstring_parser/docstring_parser.DocstringParam.html) `default` and `is_optional` fields.
    * `default` defaults to `None` if not found in doc string, what if `None` is the default value?
    * only use `is_optional`?
    * found some examples to get started within the [test files of docstring_parser](https://github.com/rr-/docstring_parser/blob/969b64467647d23cd85767b09c7fdcbacbbff0cf/docstring_parser/tests/test_rest.
    
It looks manageable and seems like a nice addition this project.

**Comment by PandasAreBears** [comment]
Hey,

Thanks for writing such a detailed issue report!

I've implemented the change in [77758e58](https://github.com/PandasAreBears/gptfunction/commit/77758e58e0fb4b1af32cf2c746aeb23cd4394991) and released [v0.2.0](https://pypi.org/project/gptfunction/0.2.0/). 

This uses `is_optional` as suggested. The feature is automatically enabled with a call to `schema()` but may be disabled with `schema(use_required=False)`.
